// filmListReducer
export const LOAD_FILMS = "LOAD_FILMS"
export const SET_STATUS = "SET_STATUS"
export const SET_ACTIVE_FILM_ID = "SET_ACTIVE_FILM_ID"
export const SET_CURRENT_FILM_STATUS = "SET_CURRENT_FILM_STATUS"
export const SET_CURRENT_FILM_DATA = "SET_CURRENT_FILM_DATA"
export const SET_DEFAULT_STATE_FILM = "SET_DEFAULT_STATE_FILM"
// formReducer
export const SET_FIELD_VALUE = "SET_FIELD_VALUE"
export const SET_FIELD_STATUS = "SET_FIELD_STATUS"
export const SET_PENDING_STATUS = "SET_PENDING_STATUS"
export const SET_DEFAULT_STATE_FORM = "SET_DEFAULT_STATE_FORM"
// stepReducer
export const SET_STEP = "SET_STEP"